apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"labels":{"app":"kube-prometheus-stack-grafana","app.kubernetes.io/instance":"monitor","chart":"kube-prometheus-stack-13.2.1","heritage":"Helm","release":"monitor"},"name":"monitor-kube-prometheus-st-grafana","namespace":"monitoring"},"spec":{"endpoints":[{"path":"/metrics","port":"service"}],"namespaceSelector":{"matchNames":["monitoring"]},"selector":{"matchLabels":{"app.kubernetes.io/instance":"monitor","app.kubernetes.io/name":"grafana"}}}}
  creationTimestamp: "2021-04-08T19:09:40Z"
  generation: 1
  labels:
    app: kube-prometheus-stack-grafana
    app.kubernetes.io/instance: monitor
    chart: kube-prometheus-stack-13.2.1
    heritage: Helm
    release: monitor
  name: monitor-kube-prometheus-st-grafana
  namespace: monitoring
  resourceVersion: "8533635"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/servicemonitors/monitor-kube-prometheus-st-grafana
  uid: 9821f9fc-5686-44fd-9d93-c3b0d0a67e83
spec:
  endpoints:
  - path: /metrics
    port: service
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: monitor
      app.kubernetes.io/name: grafana
